from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from app.services.documentary.metadata_contract import (
    ACCESS_LEVEL_VALUES,
    CITATION_POLICY_VALUES,
    DATA_TAG_VALUES,
    FAMILLE_POLITIQUE_VALUES,
    FRESHNESS_STATUS_VALUES,
    LANGUAGE_VALUES,
    MODE_QUALIFICATION_VALUES,
    NIVEAU_CONFIANCE_VALUES,
    POSITION_PROJET_VALUES,
    RIGHTS_STATUS_VALUES,
    ROLE_DOCUMENTAIRE_VALUES,
    SERVICE_FAMILY_VALUES,
    STATUT_METADONNEES_VALUES,
    TYPE_DOCUMENT_VALUES,
    USAGE_PROBATOIRE_VALUES,
    VISIBILITY_SCOPE_VALUES,
)


ALLOWED_LEVELS = {
    "document",
    "chunk",
    "index_version",
    "retrieval_run",
    "generation_run",
    "output",
}

ALLOWED_STORAGES = {
    "sql_column",
    "jsonb",
    "qdrant_payload",
    "runtime",
}

ALLOWED_USES = {
    "filtering",
    "retrieval",
    "generation",
    "display",
    "governance",
    "audit",
    "routing",
    "evaluation",
}

ALLOWED_IMPLEMENTATION_STATUSES = {
    "implemented",
    "planned",
    "partial",
    "deprecated",
}

QDRANT_REQUIRED_METADATA = {
    "chunk_id",
    "document_id",
    "source_code",
    "index_version_id",
    "role_documentaire",
    "theme_tags",
    "visibility_scope",
    "organization_id",
    "access_level",
    "data_tags",
    "service_family",
    "service_ids",
}


@dataclass(frozen=True)
class MetadataRegistryEntry:
    metadata: str
    level: str
    storage: tuple[str, ...]
    uses: tuple[str, ...]
    allowed_values: tuple[str, ...] | None = None
    default_value: Any | None = None
    propagate_to_chunk: bool = False
    propagate_to_qdrant: bool = False
    retrieval_filterable: bool = False
    qdrant_required: bool = False
    implementation_status: str = "implemented"
    deprecated: bool = False
    alias_of: str | None = None
    qdrant_without_chunk_reason: str | None = None


def _values(values: set[str]) -> tuple[str, ...]:
    return tuple(sorted(values))


METADATA_REGISTRY: tuple[MetadataRegistryEntry, ...] = (
    MetadataRegistryEntry(
        "title",
        "document",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("display", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "source_code",
        "document",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("filtering", "retrieval", "display", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "role_documentaire",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "retrieval", "display", "evaluation", "governance", "audit"),
        allowed_values=_values(ROLE_DOCUMENTAIRE_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "famille_politique",
        "document",
        ("jsonb", "qdrant_payload"),
        ("display", "governance", "audit"),
        allowed_values=_values(FAMILLE_POLITIQUE_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "positionnement",
        "document",
        ("jsonb", "qdrant_payload"),
        ("display", "governance", "audit"),
        allowed_values=_values(POSITION_PROJET_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "niveau_confiance",
        "document",
        ("jsonb", "qdrant_payload"),
        ("display", "governance", "audit"),
        allowed_values=_values(NIVEAU_CONFIANCE_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "type_document",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "governance", "audit"),
        allowed_values=_values(TYPE_DOCUMENT_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "usage_probatoire",
        "document",
        ("jsonb", "qdrant_payload"),
        ("display", "governance", "audit"),
        allowed_values=_values(USAGE_PROBATOIRE_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "statut_metadonnees",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "governance", "audit"),
        allowed_values=_values(STATUT_METADONNEES_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "mode_qualification",
        "document",
        ("jsonb", "qdrant_payload"),
        ("governance", "audit"),
        allowed_values=_values(MODE_QUALIFICATION_VALUES),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "qualification_confidence",
        "document",
        ("jsonb", "qdrant_payload"),
        ("governance", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "qualification_rationale",
        "document",
        ("jsonb", "qdrant_payload"),
        ("governance", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "validated_by",
        "document",
        ("jsonb", "qdrant_payload"),
        ("governance", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "validated_at",
        "document",
        ("jsonb", "qdrant_payload"),
        ("governance", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "theme_tags",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "retrieval", "display", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "data_tags",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "routing", "display", "audit"),
        allowed_values=_values(DATA_TAG_VALUES),
        default_value=("corpus",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "service_family",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "routing", "display", "audit"),
        allowed_values=_values(SERVICE_FAMILY_VALUES),
        default_value="transverse",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "service_ids",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "routing", "display", "audit"),
        default_value=(),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "visibility_scope",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "governance", "audit"),
        allowed_values=_values(VISIBILITY_SCOPE_VALUES),
        default_value="public",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "organization_id",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "governance", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "access_level",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "governance", "audit"),
        allowed_values=_values(ACCESS_LEVEL_VALUES),
        default_value="open",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "source_url",
        "document",
        ("jsonb", "qdrant_payload"),
        ("display", "generation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "publication_date",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "collected_at",
        "document",
        ("jsonb", "qdrant_payload"),
        ("display", "audit"),
        default_value="current UTC datetime",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "freshness_status",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "audit"),
        allowed_values=_values(FRESHNESS_STATUS_VALUES),
        default_value="unknown",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "language",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "routing", "audit"),
        allowed_values=_values(LANGUAGE_VALUES),
        default_value="fr",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
    ),
    MetadataRegistryEntry(
        "geographic_scope",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "temporal_scope",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "is_primary_source",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "display", "governance", "audit"),
        default_value=False,
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "citation_policy",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "generation", "governance", "audit"),
        allowed_values=_values(CITATION_POLICY_VALUES),
        default_value="a_verifier",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "rights_status",
        "document",
        ("jsonb", "qdrant_payload"),
        ("filtering", "generation", "governance", "audit"),
        allowed_values=_values(RIGHTS_STATUS_VALUES),
        default_value="unknown",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "extraction",
        "document",
        ("jsonb",),
        ("display", "audit"),
    ),
    MetadataRegistryEntry(
        "extracted_pages",
        "document",
        ("jsonb",),
        ("display", "audit"),
    ),
    MetadataRegistryEntry(
        "extraction.status",
        "document",
        ("jsonb",),
        ("display", "audit"),
        allowed_values=("failed", "partial", "success"),
    ),
    MetadataRegistryEntry(
        "extraction.ocr_used",
        "document",
        ("jsonb",),
        ("display", "audit"),
        default_value=False,
    ),
    MetadataRegistryEntry(
        "extraction.page_count",
        "document",
        ("jsonb",),
        ("display", "audit"),
    ),
    MetadataRegistryEntry(
        "extraction.layout_quality_status",
        "document",
        ("jsonb",),
        ("display", "audit"),
    ),
    MetadataRegistryEntry(
        "extraction.errors",
        "document",
        ("jsonb",),
        ("display", "audit"),
        default_value=(),
    ),
    MetadataRegistryEntry(
        "source_id",
        "chunk",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("display", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "document_id",
        "chunk",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("filtering", "retrieval", "display", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "parent_document_id",
        "chunk",
        ("jsonb", "qdrant_payload"),
        ("display", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "document_title",
        "chunk",
        ("jsonb", "qdrant_payload"),
        ("retrieval", "display", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "content_sha256",
        "chunk",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "content_hash",
        "chunk",
        ("jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "chunk_id",
        "chunk",
        ("sql_column", "qdrant_payload", "runtime"),
        ("retrieval", "display", "generation", "evaluation", "audit"),
        propagate_to_qdrant=True,
        qdrant_required=True,
        qdrant_without_chunk_reason=(
            "chunk_id is added as the Qdrant point mapping key, not inherited "
            "from document metadata."
        ),
    ),
    MetadataRegistryEntry(
        "chunk_index",
        "chunk",
        ("sql_column",),
        ("display", "audit"),
    ),
    MetadataRegistryEntry(
        "page_start",
        "chunk",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("display", "generation", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "page_end",
        "chunk",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("display", "generation", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "section",
        "chunk",
        ("jsonb", "qdrant_payload"),
        ("display", "audit"),
        default_value="body",
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "section_title",
        "chunk",
        ("jsonb", "qdrant_payload"),
        ("display", "generation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "token_count",
        "chunk",
        ("sql_column",),
        ("audit",),
    ),
    MetadataRegistryEntry(
        "qdrant_point_id",
        "chunk",
        ("sql_column",),
        ("retrieval", "audit"),
    ),
    MetadataRegistryEntry(
        "index_version_id",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload", "runtime"),
        ("filtering", "retrieval", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        retrieval_filterable=True,
        implementation_status="partial",
        qdrant_required=True,
    ),
    MetadataRegistryEntry(
        "vector_collection",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload", "runtime"),
        ("retrieval", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "embedding_provider",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload", "runtime"),
        ("retrieval", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "embedding_model",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload", "runtime"),
        ("retrieval", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "embedding_dimension",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload", "runtime"),
        ("retrieval", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "chunking_version",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "split_strategy",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "chunk_size",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        default_value=450,
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "chunk_overlap",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        default_value=80,
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "min_chunk_size",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        default_value=80,
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "max_chunk_size",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        default_value=650,
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "chunking_strategy",
        "index_version",
        ("sql_column", "jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        deprecated=True,
        alias_of="chunking_version",
        implementation_status="deprecated",
    ),
    MetadataRegistryEntry(
        "chunk_size_words",
        "index_version",
        ("jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        deprecated=True,
        alias_of="chunk_size",
        implementation_status="deprecated",
    ),
    MetadataRegistryEntry(
        "chunk_overlap_words",
        "index_version",
        ("jsonb", "qdrant_payload"),
        ("audit",),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
        deprecated=True,
        alias_of="chunk_overlap",
        implementation_status="deprecated",
    ),
    MetadataRegistryEntry(
        "ai_backend_preset",
        "retrieval_run",
        ("jsonb", "runtime"),
        ("routing", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "embedding_model_call_id",
        "retrieval_run",
        ("jsonb", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "reranker_provider",
        "retrieval_run",
        ("jsonb", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "reranker_model",
        "retrieval_run",
        ("jsonb", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "rerank_model_call_id",
        "retrieval_run",
        ("jsonb", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "call_type",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("routing", "audit"),
    ),
    MetadataRegistryEntry(
        "provider",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("routing", "audit"),
    ),
    MetadataRegistryEntry(
        "model",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("routing", "audit"),
    ),
    MetadataRegistryEntry(
        "input_hash",
        "retrieval_run",
        ("sql_column",),
        ("audit",),
    ),
    MetadataRegistryEntry(
        "parameters",
        "retrieval_run",
        ("sql_column", "jsonb"),
        ("audit",),
    ),
    MetadataRegistryEntry(
        "response_metadata",
        "retrieval_run",
        ("sql_column", "jsonb"),
        ("audit",),
    ),
    MetadataRegistryEntry(
        "latency_ms",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("evaluation", "audit"),
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "run_id",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("retrieval", "generation", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "retrieval_run_id",
        "generation_run",
        ("jsonb", "runtime"),
        ("generation", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "generation_run_id",
        "generation_run",
        ("sql_column", "runtime"),
        ("generation", "audit"),
    ),
    MetadataRegistryEntry(
        "model_call_id",
        "retrieval_run",
        ("sql_column", "jsonb", "qdrant_payload", "runtime"),
        ("retrieval", "generation", "evaluation", "audit"),
        propagate_to_chunk=True,
        propagate_to_qdrant=True,
    ),
    MetadataRegistryEntry(
        "prompt_version",
        "generation_run",
        ("sql_column", "jsonb", "runtime"),
        ("generation", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "llm_provider",
        "generation_run",
        ("jsonb", "runtime"),
        ("generation", "audit"),
    ),
    MetadataRegistryEntry(
        "llm_model",
        "generation_run",
        ("jsonb", "runtime"),
        ("generation", "audit"),
    ),
    MetadataRegistryEntry(
        "llm_model_call_id",
        "generation_run",
        ("sql_column", "jsonb", "runtime"),
        ("generation", "audit"),
    ),
    MetadataRegistryEntry(
        "token_input",
        "generation_run",
        ("sql_column", "runtime"),
        ("generation", "audit"),
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "token_output",
        "generation_run",
        ("sql_column", "runtime"),
        ("generation", "audit"),
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "cost_estimate",
        "generation_run",
        ("sql_column", "runtime"),
        ("generation", "audit"),
        implementation_status="partial",
    ),
    MetadataRegistryEntry(
        "rank_initial",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "rank_final",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("retrieval", "generation", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "dense_score",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "lexical_score",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
    MetadataRegistryEntry(
        "rerank_score",
        "retrieval_run",
        ("sql_column", "runtime"),
        ("retrieval", "evaluation", "audit"),
    ),
)


METADATA_REGISTRY_BY_NAME = {
    entry.metadata: entry
    for entry in METADATA_REGISTRY
}


EXPORT_COLUMNS = (
    "Metadata",
    "level",
    "storage",
    "uses",
    "implementation_status",
    "allowed_values",
    "default_value",
    "propagate_to_chunk",
    "propagate_to_qdrant",
    "retrieval_filterable",
    "qdrant_required",
)
